pygame 2.1.2 (SDL 2.0.18, Python 3.8.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Current tracking mode: Default
Compute and apply returned calibration_status_success and collected at 6 points.
Saving calibration to file 1 for eye tracker with serial number X3120-030107707753.
calibration completed
x
False
x
False
rwindows
False
y
False
1.2212 	WARNING 	Requested an unavailable screen number - using first available.
1.2219 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1707, 960]. Using actual size
Traceback (most recent call last):
  File "C:/Users/kessler_lab/Desktop/pupillometry-rf-back/demos/TheExperiement.py", line 224, in <module>
    main()
  File "C:/Users/kessler_lab/Desktop/pupillometry-rf-back/demos/TheExperiement.py", line 220, in main
    stop_and_save_logs()
  File "C:/Users/kessler_lab/Desktop/pupillometry-rf-back/demos/TheExperiement.py", line 183, in stop_and_save_logs
    f = open(settings.FILENAME + '.pkl', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'run.pkl'
